In [2]:
import pandas as pd
from pathlib import Path

# Normal Results

In [22]:
folder = Path("../ABLATIAN RESULTS/MODEL 1")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]
segment_files = [f for f in csvs if f.name.startswith("SEGMENT_")]

print("RESULT files:", len(result_files))
print("SEGMENT files:", len(segment_files))

RESULT files: 24
SEGMENT files: 24

In [23]:

# merge RESULTS
results_df = pd.concat(
    [pd.read_csv(f) for f in result_files],
    ignore_index=True
)

# merge SEGMENTS
segments_df = pd.concat(
    [pd.read_csv(f) for f in segment_files],
    ignore_index=True
)

In [24]:
results_df

,C,gamma,percentile,patient,total_length_hours,TP,FP,FN,sensitivity,precision,f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap
0,10,0.001,10,chb01,40.549306,7,6,0,1.000000,0.538462,0.700000,3.551232,0.147968,24.00,7,0.957437,0.685445
1,10,0.001,10,chb02,46.265972,0,7,3,0.000000,0.000000,0.000000,3.631178,0.151299,NaN,0,0.792279,0.144225
2,10,0.001,10,chb03,48.335417,5,19,2,0.714286,0.208333,0.322581,9.434076,0.393087,36.50,5,0.925757,0.208208
3,10,0.001,10,chb04,204.526389,4,26,0,1.000000,0.133333,0.235294,3.050951,0.127123,63.25,4,0.908047,0.239303
4,10,0.001,10,chb05,50.336806,4,9,1,0.800000,0.307692,0.444444,4.291095,0.178796,24.75,4,0.943870,0.576586
5,10,0.001,10,chb06,80.347917,2,19,8,0.200000,0.095238,0.129032,5.675318,0.236472,37.50,2,0.907566,0.136338
6,10,0.001,10,chb07,86.599306,0,15,3,0.000000,0.000000,0.000000,4.157077,0.173212,NaN,0,0.699323,0.127282
7,10,0.001,10,chb08,21.008333,4,5,1,0.800000,0.444444,0.571429,5.712019,0.238001,59.50,4,0.858271,0.543484
8,10,0.001,10,chb09,83.364583,4,13,0,1.000000,0.235294,0.380952,3.742597,0.155942,26.50,4,0.934161,0.480001
9,10,0.001,10,chb10,56.690278,6,18,1,0.857143,0.250000,0.387097,7.620354,0.317515,16.25,6,0.964814,0.601210
10,10,0.001,10,chb11,40.793056,3,5,2,0.600000,0.375000,0.461538,2.941677,0.122570,-8.50,2,0.871738,0.474805
11,10,0.001,10,chb12,22.020833,5,6,22,0.185185,0.454545,0.263158,6.539262,0.272469,24.50,5,0.847428,0.325666
12,10,0.001,10,chb13,41.333333,0,5,12,0.000000,0.000000,0.000000,2.903226,0.120968,NaN,0,0.524890,0.023749
13,10,0.001,10,chb14,32.333333,3,7,5,0.375000,0.300000,0.333333,5.195876,0.216495,11.50,3,0.891009,0.279920
14,10,0.001,10,chb15,48.343056,12,6,8,0.600000,0.666667,0.631579,2.978711,0.124113,51.50,12,0.905203,0.499268
15,10,0.001,10,chb16,23.333333,0,16,10,0.000000,0.000000,0.000000,16.457143,0.685714,NaN,0,0.664235,0.013071
16,10,0.001,10,chb17,26.216667,1,15,2,0.333333,0.062500,0.105263,13.731723,0.572155,35.00,1,0.697893,0.183115
17,10,0.001,10,chb18,45.634722,5,11,1,0.833333,0.312500,0.454545,5.785069,0.241045,14.50,5,0.828079,0.385463
18,10,0.001,10,chb19,38.928472,3,18,0,1.000000,0.142857,0.250000,11.097276,0.462386,51.00,3,0.850128,0.193240
19,10,0.001,10,chb20,34.611111,7,10,1,0.875000,0.411765,0.560000,6.934189,0.288925,26.00,7,0.975933,0.488511
20,10,0.001,10,chb21,42.496528,4,8,0,1.000000,0.333333,0.500000,4.518016,0.188251,13.75,4,0.959490,0.639249
21,10,0.001,10,chb22,40.336111,3,2,0,1.000000,0.600000,0.750000,1.190001,0.049583,32.00,3,0.951827,0.757895
22,10,0.001,10,chb23,32.422917,7,5,0,1.000000,0.583333,0.736842,3.701086,0.154212,17.50,7,0.973740,0.583039
23,10,0.001,10,chb24,24.395139,2,2,10,0.166667,0.500000,0.250000,1.967605,0.081984,25.00,2,0.857646,0.402481

In [9]:

# # sort
# results_df = results_df.sort_values(
#     by=["config", "patient"]
# ).reset_index(drop=True)

# segments_df = segments_df.sort_values(
#     by=["config", "patient"]
# ).reset_index(drop=True)


# print(results_df.shape)
# print(segments_df.shape)

In [25]:
results_df.head()

,C,gamma,percentile,patient,total_length_hours,TP,FP,FN,sensitivity,precision,f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap
0,10,0.001,10,chb01,40.549306,7,6,0,1.000000,0.538462,0.700000,3.551232,0.147968,24.00,7,0.957437,0.685445
1,10,0.001,10,chb02,46.265972,0,7,3,0.000000,0.000000,0.000000,3.631178,0.151299,NaN,0,0.792279,0.144225
2,10,0.001,10,chb03,48.335417,5,19,2,0.714286,0.208333,0.322581,9.434076,0.393087,36.50,5,0.925757,0.208208
3,10,0.001,10,chb04,204.526389,4,26,0,1.000000,0.133333,0.235294,3.050951,0.127123,63.25,4,0.908047,0.239303
4,10,0.001,10,chb05,50.336806,4,9,1,0.800000,0.307692,0.444444,4.291095,0.178796,24.75,4,0.943870,0.576586

In [26]:
segments_df.head()

,C,gamma,percentile,patient,record,n_windows,n_seizure_windows,record_length,threshold,k,roc_auc,ap,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tp,fp,fn
0,10,0.001,10,chb01,chb01_03,1437,16,3600.0,-1.063608,8,0.991819,0.510324,0.987474,0.992963,0.500000,0.444444,0.470588,8,10,8
1,10,0.001,10,chb01,chb01_04,1437,11,3600.0,-1.004783,8,0.995792,0.743831,0.987474,0.988780,0.818182,0.360000,0.500000,9,16,2
2,10,0.001,10,chb01,chb01_15,1437,16,3600.0,-1.207326,8,0.746481,0.065588,0.965205,0.975369,0.062500,0.027778,0.038462,1,35,15
3,10,0.001,10,chb01,chb01_16,1437,21,3600.0,-1.121530,8,0.989911,0.697757,0.990953,0.995056,0.714286,0.681818,0.697674,15,7,6
4,10,0.001,10,chb01,chb01_18,1437,37,3600.0,1.498560,1,0.995946,0.911562,0.990953,0.999286,0.675676,0.961538,0.793651,25,1,12

In [27]:
# save
results_df.to_csv("RESULTS_MODEL_1.csv", index=False)
segments_df.to_csv("SEGMENTS_MODEL_1.csv", index=False)

In [ ]:
results_df

# Leaky results

In [42]:
folder = Path("RESULTS_LEAKY")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
leaky_files = [f for f in csvs if f.name.startswith("LEAKY")]

In [44]:
leaky_files

[WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_10.csv'),
 WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_5.csv')]

In [47]:
# merge RESULTS
leaky_df = pd.concat(
    [pd.read_csv(f) for f in leaky_files],
    ignore_index=True
)

In [51]:
leaky_df.head()

,config,C,gamma,percentile,patient,use_all_files,n_train,n_test,test_pos,roc_auc,...,baseline_auprc,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tn,fp,fn,tp
0,A10,0.1,scale,10,chb01,False,8594,955,18,0.996443,...,0.018848,0.978010,0.977588,1.000000,0.461538,0.631579,916,21,0,18
1,B10,0.1,0.01,10,chb01,False,8594,955,18,0.996739,...,0.018848,0.982199,0.982924,0.944444,0.515152,0.666667,921,16,1,17
2,C10,0.1,0.001,10,chb01,False,8594,955,18,0.995612,...,0.018848,0.962304,0.961580,1.000000,0.333333,0.500000,901,36,0,18
3,D10,0.1,0.0001,10,chb01,False,8594,955,18,0.980730,...,0.018848,0.952880,0.954109,0.888889,0.271186,0.415584,894,43,2,16
4,E10,1.0,scale,10,chb01,False,8594,955,18,0.999051,...,0.018848,0.994764,0.995731,0.944444,0.809524,0.871795,933,4,1,17

In [53]:
leaky_df.to_csv("RESULTS_LEAKY.csv", index=False)

# Merge all Results

In [61]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]

print("RESULT files:", len(result_files))

RESULT files: 4

In [13]:
result_files

[WindowsPath('RESULTS/RESULTS_0_10%.csv'),
 WindowsPath('RESULTS/RESULTS_0_5%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_10%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_5%.csv')]

In [21]:
results_0_10 = pd.read_csv(result_files[0]) 
results_0_5 = pd.read_csv(result_files[1]) 
results_10_10 = pd.read_csv(result_files[2]) 
results_10_5 = pd.read_csv(result_files[3])

In [38]:
results_0_10['windows']=0
results_0_5['windows']=0
results_10_10['windows']=10000
results_10_5['windows']=10000

In [39]:
results_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap',
       'windows'],
      dtype='object')

In [40]:
a=results_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

b=results_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

c=results_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

d=results_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

In [43]:
RESULTS = pd.concat([a,b,c,d], ignore_index=False)

In [46]:
RESULTS.to_csv("EVENT_LEVEL_RESULTS.csv", index=False)

# Merge all segments

In [55]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))

# split by filename
segment_files = [f for f in csvs if f.name.startswith("SEGMENTS_")]

print("SEGMENT files:", len(segment_files))

SEGMENT files: 4

In [56]:
segment_files

[WindowsPath('RESULTS/SEGMENTS_0_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_0_5%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_5%.csv')]

In [57]:
segments_0_10 = pd.read_csv(segment_files[0]) 
segments_0_5 = pd.read_csv(segment_files[1]) 
segments_10_10 = pd.read_csv(segment_files[2]) 
segments_10_5 = pd.read_csv(segment_files[3])

In [58]:
segments_0_10['windows']=0
segments_0_5['windows']=0
segments_10_10['windows']=10000
segments_10_5['windows']=10000

In [59]:
segments_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows'],
      dtype='object')

In [60]:
a=segments_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

b=segments_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

c=segments_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

d=segments_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

In [62]:
SEGMENTS = pd.concat([a,b,c,d], ignore_index=False)

In [63]:
SEGMENTS.to_csv("SEGMENT_LEVEL_RESULTS.csv", index=False)