In [1]:
import pandas as pd
from pathlib import Path

<!-- # Normal Results -->

In [2]:
folder = Path("../RESULTADOS MODELO GOF FINAL")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("EVENTS_")]
segment_files = [f for f in csvs if f.name.startswith("FALSE_")]

print("RESULT files:", len(result_files))
print("SEGMENT files:", len(segment_files))

RESULT files: 24
SEGMENT files: 24

In [3]:

# merge RESULTS
results_df = pd.concat(
    [pd.read_csv(f) for f in result_files],
    ignore_index=True
)

# merge SEGMENTS
segments_df = pd.concat(
    [pd.read_csv(f) for f in segment_files],
    ignore_index=True
)

In [5]:
results_df

,patient,record,event_start,event_end,detected,latency_s,threshold,k,k_feat
0,chb01,chb01_03,2996.0,3036.0,1,14.0,0.0,3,60
1,chb01,chb01_04,1467.0,1494.0,1,10.5,0.0,3,80
2,chb01,chb01_15,1732.0,1772.0,1,48.0,0.0,3,60
3,chb01,chb01_16,1015.0,1066.0,1,-2.5,0.0,3,60
4,chb01,chb01_18,1720.0,1810.0,1,10.0,0.0,3,40
...,...,...,...,...,...,...,...,...,...
176,chb24,chb24_13,3288.0,3304.0,0,NaN,0.0,4,100
177,chb24,chb24_14,1939.0,1966.0,1,18.5,0.0,4,100
178,chb24,chb24_15,3552.0,3569.0,1,13.0,0.0,4,100
179,chb24,chb24_17,3515.0,3581.0,1,17.5,0.0,4,80
180,chb24,chb24_21,2804.0,2872.0,0,NaN,0.0,4,100

In [7]:
segment_summ = (
    segments_df.groupby("patient")
      .agg(
          sensitivity=("seg_sensitivity", "mean"),
          precision=("seg_precision", "mean"),
          f1=("seg_f1", "mean"),
          tp=("tp", "mean"),
          fp=("fp", "mean"),
          fn=("fn", "mean"),
      )
      .sort_values("f1", ascending=False)
)

segment_summ

         sensitivity  precision        f1         tp         fp         fn
patient
chb22       0.690900   0.861616  0.758076   1.870968   3.677419   0.806452
chb05       0.621810   0.590341  0.585783   3.538462  15.538462   2.205128
chb21       0.583949   0.642029  0.574142   1.454545   6.606061   0.939394
chb23       0.737719   0.529615  0.567827  12.666667  37.444444   6.555556
chb10       0.563107   0.531816  0.520806   4.160000   7.720000   2.920000
chb01       0.665948   0.479723  0.519874   3.119048   7.261905   1.166667
chb24       0.523193   0.757092  0.518327   3.090909   5.227273   4.590909
chb20       0.494444   0.438750  0.502910   2.068966  14.034483   2.034483
chb08       0.462440   0.568158  0.495659   8.250000  25.400000  10.100000
chb18       0.378603   0.637596  0.444411   1.472222   4.750000   2.055556
chb09       0.457949   0.541601  0.437502   2.947368  10.789474   2.894737
chb15       0.466612   0.368907  0.417791  11.000000  42.375000   9.025000
chb11       0.714115   0.481976  0.395383   2.485714  14.428571   6.742857
chb12       0.470240   0.417094  0.394678   7.952381  31.285714  11.142857
chb14       0.301937   0.309701  0.320290   0.692308   9.038462   1.923077
chb17       0.199583   0.486975  0.263285   1.047619  12.190476   4.571429
chb02       0.275253   0.252843  0.210027   0.555556  11.277778   1.388889
chb07       0.281184   0.248937  0.205674   2.000000  59.473684   5.894737
chb03       0.323063   0.171616  0.203357   1.394737  24.552632   2.894737
chb19       0.281851   0.158394  0.200369   0.900000  27.333333   2.266667
chb04       0.357576   0.153227  0.180912   0.880952  46.071429   2.738095
chb06       0.384774   0.087535  0.156443   1.222222  19.222222   2.333333
chb13       0.136667   0.018899  0.074197   0.787879  29.272727   5.757576
chb16       0.041667   0.005952  0.062500   0.052632  12.473684   2.000000

In [6]:
# save
results_df.to_csv("EVENTS_MAIN_MODEL.csv", index=False)
segments_df.to_csv("FALSE_POSITIVES_MAIN_MODEL.csv", index=False)

In [ ]:
results_df

,C,gamma,k_feat,patient,total_length_hours,TP,FP,FN,sensitivity,precision,...,sample_f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap,sens_k1,f1_k1,fpday_k1
0,100.0,0.0001,20,chb01,40.549306,7,35,0,1.000000,0.166667,...,0.174322,20.715521,0.863147,13.00,7,0.914364,0.573435,1.0,0.043887,180.520971
1,1000.0,0.0010,100,chb02,46.265972,2,16,1,0.666667,0.111111,...,0.185455,8.299836,0.345827,40.25,2,0.786553,0.218043,1.0,0.046154,64.323732
2,1000.0,0.0001,20,chb03,48.335417,5,40,2,0.714286,0.111111,...,0.087244,19.861213,0.827551,63.00,5,0.899301,0.171053,1.0,0.028398,237.838024
3,1.0,0.0010,40,chb04,204.526389,3,73,1,0.750000,0.039474,...,0.057708,8.566132,0.356922,-2.00,3,0.902198,0.221388,1.0,0.003571,261.912413
4,0.1,0.0010,60,chb05,50.336806,5,20,0,1.000000,0.200000,...,0.506977,9.535766,0.397324,21.50,5,0.941492,0.609935,1.0,0.022272,209.310064

In [ ]:
segments_df[segments_df['patient']=='chb03'][['tp','fp','fn','seg_sensitivity','seg_precision','seg_f1']]

     tp   fp  fn  seg_sensitivity  seg_precision    seg_f1
78   13  112   8         0.619048       0.104000  0.178082
79   24  285   2         0.923077       0.077670  0.143284
80    2    6  26         0.071429       0.250000  0.111111
81   19  229   2         0.904762       0.076613  0.141264
82    6   93  13         0.315789       0.060606  0.101695
83   16   78  10         0.615385       0.170213  0.266667
84   19  285   3         0.863636       0.062500  0.116564
85    0   57   0              NaN            NaN       NaN
86    0   85   0              NaN            NaN       NaN
87    0   51   0              NaN            NaN       NaN
88    0   33   0              NaN            NaN       NaN
89    0   45   0              NaN            NaN       NaN
90    0  162   0              NaN            NaN       NaN
91    0   29   0              NaN            NaN       NaN
92    0   28   0              NaN            NaN       NaN
93    0    8   0              NaN            NaN       NaN
94    0   14   0              NaN            NaN       NaN
95    0   15   0              NaN            NaN       NaN
96    0   82   0              NaN            NaN       NaN
97    0  336   0              NaN            NaN       NaN
98    0   84   0              NaN            NaN       NaN
99    0  281   0              NaN            NaN       NaN
100   0  587   0              NaN            NaN       NaN
101   0  360   0              NaN            NaN       NaN
102   0  229   0              NaN            NaN       NaN
103   0  290   0              NaN            NaN       NaN
104   0  318   0              NaN            NaN       NaN
105   0  394   0              NaN            NaN       NaN
106   0  331   0              NaN            NaN       NaN
107   0  295   0              NaN            NaN       NaN
108   0  176   0              NaN            NaN       NaN
109   0  159   0              NaN            NaN       NaN
110   0  165   0              NaN            NaN       NaN
111   0  333   0              NaN            NaN       NaN
112   0  447   0              NaN            NaN       NaN
113   0  288   0              NaN            NaN       NaN
114   0   44   0              NaN            NaN       NaN
115   0  204   0              NaN            NaN       NaN

In [ ]:
import time
from sklearn.svm import SVC
print(X_big.shape)          # how big is n, really?
t = time.time()
SVC(C=10, gamma=0.01, kernel='rbf', cache_size=1000).fit(X_big, y_big)
print(time.time() - t, "s")

NameError: name 'X_big' is not defined

<!-- # Leaky results -->

In [ ]:
folder = Path("RESULTS_LEAKY")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
leaky_files = [f for f in csvs if f.name.startswith("LEAKY")]

In [ ]:
leaky_files

[WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_10.csv'),
 WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_5.csv')]

In [ ]:
# merge RESULTS
leaky_df = pd.concat(
    [pd.read_csv(f) for f in leaky_files],
    ignore_index=True
)

In [ ]:
leaky_df.head()

,config,C,gamma,percentile,patient,use_all_files,n_train,n_test,test_pos,roc_auc,...,baseline_auprc,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tn,fp,fn,tp
0,A10,0.1,scale,10,chb01,False,8594,955,18,0.996443,...,0.018848,0.978010,0.977588,1.000000,0.461538,0.631579,916,21,0,18
1,B10,0.1,0.01,10,chb01,False,8594,955,18,0.996739,...,0.018848,0.982199,0.982924,0.944444,0.515152,0.666667,921,16,1,17
2,C10,0.1,0.001,10,chb01,False,8594,955,18,0.995612,...,0.018848,0.962304,0.961580,1.000000,0.333333,0.500000,901,36,0,18
3,D10,0.1,0.0001,10,chb01,False,8594,955,18,0.980730,...,0.018848,0.952880,0.954109,0.888889,0.271186,0.415584,894,43,2,16
4,E10,1.0,scale,10,chb01,False,8594,955,18,0.999051,...,0.018848,0.994764,0.995731,0.944444,0.809524,0.871795,933,4,1,17

In [ ]:
leaky_df.to_csv("RESULTS_LEAKY.csv", index=False)

<!-- # Merge all Results -->

In [ ]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]

print("RESULT files:", len(result_files))

RESULT files: 4

In [ ]:
result_files

[WindowsPath('RESULTS/RESULTS_0_10%.csv'),
 WindowsPath('RESULTS/RESULTS_0_5%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_10%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_5%.csv')]

In [ ]:
results_0_10 = pd.read_csv(result_files[0]) 
results_0_5 = pd.read_csv(result_files[1]) 
results_10_10 = pd.read_csv(result_files[2]) 
results_10_5 = pd.read_csv(result_files[3])

In [ ]:
results_0_10['windows']=0
results_0_5['windows']=0
results_10_10['windows']=10000
results_10_5['windows']=10000

In [ ]:
results_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap',
       'windows'],
      dtype='object')

In [ ]:
a=results_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

b=results_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

c=results_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

d=results_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

In [ ]:
RESULTS = pd.concat([a,b,c,d], ignore_index=False)

In [ ]:
RESULTS.to_csv("EVENT_LEVEL_RESULTS.csv", index=False)

<!-- # Merge all segments -->

In [ ]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))

# split by filename
segment_files = [f for f in csvs if f.name.startswith("SEGMENTS_")]

print("SEGMENT files:", len(segment_files))

SEGMENT files: 4

In [ ]:
segment_files

[WindowsPath('RESULTS/SEGMENTS_0_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_0_5%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_5%.csv')]

In [ ]:
segments_0_10 = pd.read_csv(segment_files[0]) 
segments_0_5 = pd.read_csv(segment_files[1]) 
segments_10_10 = pd.read_csv(segment_files[2]) 
segments_10_5 = pd.read_csv(segment_files[3])

In [ ]:
segments_0_10['windows']=0
segments_0_5['windows']=0
segments_10_10['windows']=10000
segments_10_5['windows']=10000

In [ ]:
segments_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows'],
      dtype='object')

In [ ]:
a=segments_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

b=segments_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

c=segments_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

d=segments_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

In [ ]:
SEGMENTS = pd.concat([a,b,c,d], ignore_index=False)

In [ ]:
SEGMENTS.to_csv("SEGMENT_LEVEL_RESULTS.csv", index=False)

<!-- # Other -->

In [ ]:
import pandas as pd

df = pd.read_csv("../RESULTS/BEFORE/0_SEGMENTS.csv")

summary = (
    df.groupby("patient", as_index=False)[["n_windows", "n_seizure_windows"]]
      .sum()
)

summary

   patient  n_windows  n_seizure_windows
0    chb01      58265                180
1    chb02      66515                 70
2    chb03      69489                163
3    chb04     294392                152
4    chb05      72368                224
5    chb06     115647                 64
6    chb07     124646                150
7    chb08      30192                367
8    chb09     119988                111
9    chb10      81559                177
10   chb11      58637                323
11   chb12      31647                401
12   chb13      59421                216
13   chb14      46482                 68
14   chb15      69494                801
15   chb16      33543                 39
16   chb17      37689                118
17   chb18      65606                127
18   chb19      55967                 95
19   chb20      49753                119
20   chb21      61096                 79
21   chb22      57991                 83
22   chb23      46662                173
23   chb24      35063                169

In [ ]:
import pandas as pd

df = pd.read_csv("../RESULTS/BEFORE/0_SEGMENTS.csv")

summary = (
    df.groupby("patient")
      .agg(
          Records=("record", "count"),
          Total_Windows=("n_windows", "sum"),
          Seizure_Windows=("n_seizure_windows", "sum"),
      )
      .reset_index()
)

summary["Seizure_Windows (%)"] = (
    100 * summary["Seizure_Windows"] / summary["Total_Windows"]
)

summary

   patient  Records  Total_Windows  Seizure_Windows  Seizure_Windows (%)
0    chb01       42          58265              180             0.308933
1    chb02       36          66515               70             0.105239
2    chb03       38          69489              163             0.234570
3    chb04       42         294392              152             0.051632
4    chb05       39          72368              224             0.309529
5    chb06       18         115647               64             0.055341
6    chb07       19         124646              150             0.120341
7    chb08       20          30192              367             1.215554
8    chb09       19         119988              111             0.092509
9    chb10       25          81559              177             0.217021
10   chb11       35          58637              323             0.550847
11   chb12       21          31647              401             1.267103
12   chb13       33          59421              216             0.363508
13   chb14       26          46482               68             0.146293
14   chb15       40          69494              801             1.152617
15   chb16       19          33543               39             0.116269
16   chb17       21          37689              118             0.313089
17   chb18       36          65606              127             0.193580
18   chb19       30          55967               95             0.169743
19   chb20       29          49753              119             0.239182
20   chb21       33          61096               79             0.129305
21   chb22       31          57991               83             0.143126
22   chb23        9          46662              173             0.370751
23   chb24       22          35063              169             0.481990

In [ ]:
results = pd.read_csv("../RESULTS/BEFORE/0_RESULTS.csv")

n_seizures = (
    results.groupby("patient")[["TP", "FN"]]
           .sum()
)

n_seizures["Seizures"] = n_seizures["TP"] + n_seizures["FN"]

summary = summary.merge(
    n_seizures[["Seizures"]],
    on="patient",
    how="left"
)

summary

,patient,Records,Total_Windows,Seizure_Windows,Seizure_Windows (%),Seizures
0,chb01,42,58265,180,0.308933,7
1,chb02,36,66515,70,0.105239,3
2,chb03,38,69489,163,0.234570,7
3,chb04,42,294392,152,0.051632,4
4,chb05,39,72368,224,0.309529,5
5,chb06,18,115647,64,0.055341,10
6,chb07,19,124646,150,0.120341,3
7,chb08,20,30192,367,1.215554,5
8,chb09,19,119988,111,0.092509,4
9,chb10,25,81559,177,0.217021,7
10,chb11,35,58637,323,0.550847,5
11,chb12,21,31647,401,1.267103,27
12,chb13,33,59421,216,0.363508,12
13,chb14,26,46482,68,0.146293,8
14,chb15,40,69494,801,1.152617,20
15,chb16,19,33543,39,0.116269,10
16,chb17,21,37689,118,0.313089,3
17,chb18,36,65606,127,0.193580,6
18,chb19,30,55967,95,0.169743,3
19,chb20,29,49753,119,0.239182,8
20,chb21,33,61096,79,0.129305,4
21,chb22,31,57991,83,0.143126,3
22,chb23,9,46662,173,0.370751,7
23,chb24,22,35063,169,0.481990,12