In [2]:
import pandas as pd
from pathlib import Path

# Normal Results

In [4]:
folder = Path("RESULTS_0")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]
segment_files = [f for f in csvs if f.name.startswith("SEGMENT_")]

print("RESULT files:", len(result_files))
print("SEGMENT files:", len(segment_files))

RESULT files: 24
SEGMENT files: 24

In [5]:

# merge RESULTS
results_df = pd.concat(
    [pd.read_csv(f) for f in result_files],
    ignore_index=True
)

# merge SEGMENTS
segments_df = pd.concat(
    [pd.read_csv(f) for f in segment_files],
    ignore_index=True
)

In [6]:

# sort
results_df = results_df.sort_values(
    by=["config", "patient"]
).reset_index(drop=True)

segments_df = segments_df.sort_values(
    by=["config", "patient"]
).reset_index(drop=True)


print(results_df.shape)
print(segments_df.shape)

(576, 18)
(16392, 21)

In [31]:
results_df.head()

,config,C,gamma,percentile,patient,total_length_hours,TP,FP,FN,sensitivity,precision,f1,FP/day,FP/hour,latency_median,n_detected,mean_fold_roc_auc,mean_fold_ap
0,A10,0.1,scale,10,chb01,40.549306,7,6,0,1.000000,0.538462,0.700000,3.551232,0.147968,25.50,7,0.947481,0.627948
1,A10,0.1,scale,10,chb02,46.265972,0,1,3,0.000000,0.000000,0.000000,0.518740,0.021614,NaN,0,0.717738,0.084852
2,A10,0.1,scale,10,chb03,48.335417,4,5,3,0.571429,0.444444,0.500000,2.482652,0.103444,49.25,4,0.937901,0.256172
3,A10,0.1,scale,10,chb04,204.526389,2,18,2,0.500000,0.100000,0.166667,2.112197,0.088008,29.75,2,0.889838,0.235757
4,A10,0.1,scale,10,chb05,50.336806,5,45,0,1.000000,0.100000,0.181818,21.455474,0.893978,45.50,5,0.946701,0.593592

In [32]:
segments_df.head()

,config,C,gamma,percentile,patient,record,n_windows,n_seizure_windows,record_length,threshold,...,roc_auc,ap,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tp,fp,fn
0,A10,0.1,scale,10,chb01,chb01_03,1437,16,3600.0,0.321063,...,0.989532,0.494611,0.981211,0.981703,0.9375,0.365854,0.526316,15,26,1
1,A10,0.1,scale,10,chb01,chb01_04,1437,11,3600.0,0.335537,...,0.986612,0.420146,0.959638,0.959327,1.0000,0.159420,0.275000,11,58,0
2,A10,0.1,scale,10,chb01,chb01_15,1437,16,3600.0,0.333578,...,0.681650,0.027793,0.944328,0.953554,0.1250,0.029412,0.047619,2,66,14
3,A10,0.1,scale,10,chb01,chb01_16,1437,21,3600.0,0.355010,...,0.993072,0.567960,0.972860,0.972458,1.0000,0.350000,0.518519,21,39,0
4,A10,0.1,scale,10,chb01,chb01_18,1437,37,3600.0,0.302808,...,0.998668,0.953494,0.986778,0.986429,1.0000,0.660714,0.795699,37,19,0

In [7]:
segments_10 = segments_df[segments_df['config'].str.endswith('10')].copy()
results_10 = results_df[results_df['config'].str.endswith('10')].copy()

In [8]:
segments_5 = segments_df[segments_df['config'].str.endswith('5')].copy()
results_5 = results_df[results_df['config'].str.endswith('5')].copy()

In [10]:
segments_5

,config,C,gamma,percentile,patient,record,n_windows,n_seizure_windows,record_length,threshold,...,roc_auc,ap,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tp,fp,fn
683,A5,0.1,scale,5,chb01,chb01_03,1437,16,3600.0,1.213848,...,0.991555,0.504203,0.981907,0.982407,0.9375,0.375000,0.535714,15,25,1
684,A5,0.1,scale,5,chb01,chb01_04,1437,11,3600.0,0.334275,...,0.986549,0.341799,0.960334,0.960028,1.0000,0.161765,0.278481,11,57,0
685,A5,0.1,scale,5,chb01,chb01_15,1437,16,3600.0,0.157556,...,0.753695,0.029806,0.945720,0.954961,0.1250,0.030303,0.048780,2,64,14
686,A5,0.1,scale,5,chb01,chb01_16,1437,21,3600.0,1.245274,...,0.993644,0.601757,0.977035,0.976695,1.0000,0.388889,0.560000,21,33,0
687,A5,0.1,scale,5,chb01,chb01_18,1437,37,3600.0,0.303364,...,0.997394,0.909361,0.986082,0.985714,1.0000,0.649123,0.787234,37,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16387,L5,10.0,0.0001,5,chb24,chb24_16,1917,0,4800.0,6.315229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,35,0
16388,L5,10.0,0.0001,5,chb24,chb24_18,1917,0,4800.0,6.329423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,101,0
16389,L5,10.0,0.0001,5,chb24,chb24_19,1917,0,4800.0,6.414440,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,67,0
16390,L5,10.0,0.0001,5,chb24,chb24_20,1917,0,4800.0,6.296270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,37,0
16391,L5,10.0,0.0001,5,chb24,chb24_22,566,0,1422.5,5.061070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,38,0

In [11]:
# save
results_5.to_csv("RESULTS_0_5%.csv", index=False)
segments_5.to_csv("SEGMENTS_0_5%.csv", index=False)

In [ ]:
results_df

# Leaky results

In [42]:
folder = Path("RESULTS_LEAKY")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
leaky_files = [f for f in csvs if f.name.startswith("LEAKY")]

In [44]:
leaky_files

[WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_10.csv'),
 WindowsPath('RESULTS_LEAKY/LEAKY_BALANCED_5.csv')]

In [47]:
# merge RESULTS
leaky_df = pd.concat(
    [pd.read_csv(f) for f in leaky_files],
    ignore_index=True
)

In [51]:
leaky_df.head()

,config,C,gamma,percentile,patient,use_all_files,n_train,n_test,test_pos,roc_auc,...,baseline_auprc,seg_accuracy,seg_specificity,seg_sensitivity,seg_precision,seg_f1,tn,fp,fn,tp
0,A10,0.1,scale,10,chb01,False,8594,955,18,0.996443,...,0.018848,0.978010,0.977588,1.000000,0.461538,0.631579,916,21,0,18
1,B10,0.1,0.01,10,chb01,False,8594,955,18,0.996739,...,0.018848,0.982199,0.982924,0.944444,0.515152,0.666667,921,16,1,17
2,C10,0.1,0.001,10,chb01,False,8594,955,18,0.995612,...,0.018848,0.962304,0.961580,1.000000,0.333333,0.500000,901,36,0,18
3,D10,0.1,0.0001,10,chb01,False,8594,955,18,0.980730,...,0.018848,0.952880,0.954109,0.888889,0.271186,0.415584,894,43,2,16
4,E10,1.0,scale,10,chb01,False,8594,955,18,0.999051,...,0.018848,0.994764,0.995731,0.944444,0.809524,0.871795,933,4,1,17

In [53]:
leaky_df.to_csv("RESULTS_LEAKY.csv", index=False)

# Merge all Results

In [61]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))


# split by filename
result_files = [f for f in csvs if f.name.startswith("RESULTS_")]

print("RESULT files:", len(result_files))

RESULT files: 4

In [13]:
result_files

[WindowsPath('RESULTS/RESULTS_0_10%.csv'),
 WindowsPath('RESULTS/RESULTS_0_5%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_10%.csv'),
 WindowsPath('RESULTS/RESULTS_10K_5%.csv')]

In [21]:
results_0_10 = pd.read_csv(result_files[0]) 
results_0_5 = pd.read_csv(result_files[1]) 
results_10_10 = pd.read_csv(result_files[2]) 
results_10_5 = pd.read_csv(result_files[3])

In [38]:
results_0_10['windows']=0
results_0_5['windows']=0
results_10_10['windows']=10000
results_10_5['windows']=10000

In [39]:
results_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap',
       'windows'],
      dtype='object')

In [40]:
a=results_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

b=results_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

c=results_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

d=results_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'total_length_hours',
       'TP', 'FP', 'FN', 'sensitivity', 'precision', 'f1', 'FP/day', 'FP/hour',
       'latency_median', 'n_detected', 'mean_fold_roc_auc', 'mean_fold_ap']].copy()

In [43]:
RESULTS = pd.concat([a,b,c,d], ignore_index=False)

In [46]:
RESULTS.to_csv("EVENT_LEVEL_RESULTS.csv", index=False)

# Merge all segments

In [55]:
folder = Path("RESULTS")

# get all csv files
csvs = list(folder.glob("*.csv"))

# split by filename
segment_files = [f for f in csvs if f.name.startswith("SEGMENTS_")]

print("SEGMENT files:", len(segment_files))

SEGMENT files: 4

In [56]:
segment_files

[WindowsPath('RESULTS/SEGMENTS_0_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_0_5%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_10%.csv'),
 WindowsPath('RESULTS/SEGMENTS_10K_5%.csv')]

In [57]:
segments_0_10 = pd.read_csv(segment_files[0]) 
segments_0_5 = pd.read_csv(segment_files[1]) 
segments_10_10 = pd.read_csv(segment_files[2]) 
segments_10_5 = pd.read_csv(segment_files[3])

In [58]:
segments_0_10['windows']=0
segments_0_5['windows']=0
segments_10_10['windows']=10000
segments_10_5['windows']=10000

In [59]:
segments_10_5.columns

Index(['config', 'C', 'gamma', 'percentile', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows'],
      dtype='object')

In [60]:
a=segments_0_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

b=segments_0_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

c=segments_10_10[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

d=segments_10_5[['windows', 'percentile','config', 'C', 'gamma', 'patient', 'record', 'n_windows',
       'n_seizure_windows', 'record_length', 'threshold', 'k', 'roc_auc', 'ap',
       'seg_accuracy', 'seg_specificity', 'seg_sensitivity', 'seg_precision',
       'seg_f1', 'tp', 'fp', 'fn', 'windows']].copy()

In [62]:
SEGMENTS = pd.concat([a,b,c,d], ignore_index=False)

In [63]:
SEGMENTS.to_csv("SEGMENT_LEVEL_RESULTS.csv", index=False)